### ISSUE TITLE
Bug:In fetch module ,I can't connect with Google 

### ISSUE THREAD

**Issue by LinLL** [RickGray/BeeCli#1]
Dear Author:
When I excute "beecli.py fetch -o test_google 'intext:Powered by PHPCMS V9'", the exception occured like this:
'do_handshake_on_connect should not be specified for non-blocking sockets',)
Traceback (most recent call last):
  File "G:/BeeCli-master/beecli.py", line 29, in <module>
    fetch_work(args)
  File "G:\BeeCli-master\lib\core\fetch.py", line 147, in fetch_work
    google = Google(debug_mode=debug)
  File "G:\BeeCli-master\lib\core\fetch.py", line 44, in **init**
    self._init()
  File "G:\BeeCli-master\lib\core\fetch.py", line 52, in _init
    raise GoogleSearchInitError('ConnectionError with "%s"' % self.host)
 lib.core.fetch.GoogleSearchInitError: ConnectionError with "https://www.google.com"
Do u know what troubles it is?

**Comment by rickvip** [comment]
You may need to check if your environment is supported Python OpenSSL.

Or, `pip install requests[security]` then try again.
